# coding: utf-8

"""
    Vortex Password Manager

    Agent credential broker. Use injects the secret at the edge. Responses never include vault material. CLI, MCP, and generated SDKs are projections of this contract.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from vortex_pwm.models.owner import Owner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Item(BaseModel):
    """
    Item
    """ # noqa: E501
    id: StrictStr
    org_id: StrictStr
    name: StrictStr
    kind: StrictStr
    owner: Owner
    uris: List[StrictStr]
    tags: Optional[List[StrictStr]] = None
    archived: Optional[StrictBool] = None
    has_totp: Optional[StrictBool] = None
    has_file: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["id", "org_id", "name", "kind", "owner", "uris", "tags", "archived", "has_totp", "has_file"]

    @field_validator('kind')
    def kind_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['api_key', 'oauth', 'ssh', 'file']):
            raise ValueError("must be one of enum values ('api_key', 'oauth', 'ssh', 'file')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Item from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of owner
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Item from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "org_id": obj.get("org_id"),
            "name": obj.get("name"),
            "kind": obj.get("kind"),
            "owner": Owner.from_dict(obj["owner"]) if obj.get("owner") is not None else None,
            "uris": obj.get("uris"),
            "tags": obj.get("tags"),
            "archived": obj.get("archived"),
            "has_totp": obj.get("has_totp"),
            "has_file": obj.get("has_file")
        })
        return _obj


