// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://veil.nyc' | (string & {});
};

export type Item = {
    id: string;
    org_id: string;
    name: string;
    kind: 'api_key' | 'oauth' | 'ssh' | 'file';
    owner: Owner;
    uris: Array<string>;
    tags?: Array<string>;
    archived?: boolean;
    has_totp?: boolean;
    has_file?: boolean;
};

export type Owner = {
    kind: string;
    id: string;
};

export type ItemsResponse = {
    items: Array<Item>;
};

export type UseRequest = {
    /**
     * Granted item name
     */
    item: string;
    /**
     * Absolute URL. Host must match the item.
     */
    url: string;
    method?: string;
    /**
     * Extra request headers. Never the vault secret.
     */
    headers?: {
        [key: string]: string;
    };
    /**
     * Request body. Never the vault secret. Use --body-file on the CLI.
     */
    body?: string;
};

export type UseResponse = {
    decision: 'allow' | 'deny' | 'need_approval';
    reason?: string;
    approval_id?: string;
    status?: number;
    /**
     * Upstream body with vault secrets scrubbed.
     */
    body?: string;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * ok
     */
    200: string;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetOpenApiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/openapi.json';
};

export type GetOpenApiResponses = {
    /**
     * OpenAPI document
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetOpenApiResponse = GetOpenApiResponses[keyof GetOpenApiResponses];

export type ListItemsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/items';
};

export type ListItemsErrors = {
    /**
     * missing or invalid Bearer
     */
    401: unknown;
};

export type ListItemsResponses = {
    /**
     * Granted items
     */
    200: ItemsResponse;
};

export type ListItemsResponse = ListItemsResponses[keyof ListItemsResponses];

export type UseItemData = {
    body: UseRequest;
    path?: never;
    query?: never;
    url: '/v1/use';
};

export type UseItemErrors = {
    /**
     * bad request
     */
    400: unknown;
    /**
     * missing or invalid Bearer
     */
    401: unknown;
};

export type UseItemResponses = {
    /**
     * Decision plus upstream result, scrubbed
     */
    200: UseResponse;
};

export type UseItemResponse = UseItemResponses[keyof UseItemResponses];
