// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID        string
	OrgID     string
	OwnerKind string
	OwnerID   string
	RevokedAt pgtype.Timestamptz
}

type Approval struct {
	GrantID   string
	ID        string
	HumanID   string
	ExpiresAt pgtype.Timestamptz
}

type Audit struct {
	ID         int64
	At         pgtype.Timestamptz
	OrgID      string
	AgentID    string
	ItemID     string
	Action     string
	Decision   string
	Reason     string
	ApprovalID string
}

type Grant struct {
	ID        string
	OrgID     string
	AgentID   string
	ItemID    string
	Level     string
	Actions   string
	ExpiresAt pgtype.Timestamptz
}

type Human struct {
	ID    string
	OrgID string
}

type Item struct {
	ID        string
	OrgID     string
	Name      string
	Kind      string
	OwnerKind string
	OwnerID   string
	Uris      string
	Secret    []byte
	HasTotp   bool
	Tags      string
	Archived  bool
	HasFile   bool
	Login     string
}

type ItemVersion struct {
	ID     int64
	ItemID string
	At     pgtype.Timestamptz
	Secret []byte
}

type OwnerKey struct {
	OwnerKind string
	OwnerID   string
	Wrapped   []byte
}

type Session struct {
	ID         string
	OrgID      string
	AgentID    string
	SecretHash []byte
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	RenewedAt  pgtype.Timestamptz
	Ttl        int64
	MaxTtl     int64
	MaxUses    int32
	Uses       int32
}

type Workload struct {
	Issuer   string
	Subject  string
	AgentID  string
	Audience string
}
