// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeSession = `-- name: ConsumeSession :one
UPDATE sessions s
SET uses = uses + 1
FROM agents a
WHERE s.secret_hash = $1::bytea
  AND s.agent_id = a.id
  AND a.revoked_at IS NULL
  AND s.expires_at > $2::timestamptz
  AND s.revoked_at IS NULL
  AND (s.max_uses = 0 OR s.uses < s.max_uses)
RETURNING a.id AS agent_id, a.org_id AS agent_org_id, a.owner_kind AS agent_owner_kind, a.owner_id AS agent_owner_id, a.revoked_at AS agent_revoked_at
`

type ConsumeSessionParams struct {
	SessionHash []byte
	Now         pgtype.Timestamptz
}

type ConsumeSessionRow struct {
	AgentID        string
	AgentOrgID     string
	AgentOwnerKind string
	AgentOwnerID   string
	AgentRevokedAt pgtype.Timestamptz
}

func (q *Queries) ConsumeSession(ctx context.Context, arg ConsumeSessionParams) (ConsumeSessionRow, error) {
	row := q.db.QueryRow(ctx, consumeSession, arg.SessionHash, arg.Now)
	var i ConsumeSessionRow
	err := row.Scan(
		&i.AgentID,
		&i.AgentOrgID,
		&i.AgentOwnerKind,
		&i.AgentOwnerID,
		&i.AgentRevokedAt,
	)
	return i, err
}

const useAuth = `-- name: UseAuth :one
SELECT
    a.id AS agent_id,
    a.org_id AS agent_org_id,
    a.owner_kind AS agent_owner_kind,
    a.owner_id AS agent_owner_id,
    a.revoked_at AS agent_revoked_at,
    i.id AS item_id,
    i.org_id AS item_org_id,
    i.name AS item_name,
    i.kind AS item_kind,
    i.owner_kind AS item_owner_kind,
    i.owner_id AS item_owner_id,
    i.uris AS item_uris,
    i.has_totp AS item_has_totp,
    i.tags AS item_tags,
    i.archived AS item_archived,
    i.has_file AS item_has_file,
    i.login AS item_login,
    g.id AS grant_id,
    g.org_id AS grant_org_id,
    g.agent_id AS grant_agent_id,
    g.item_id AS grant_item_id,
    g.level AS grant_level,
    g.actions AS grant_actions,
    g.expires_at AS grant_expires_at,
    ap.id AS approval_id,
    ap.grant_id AS approval_grant_id,
    ap.human_id AS approval_human_id,
    ap.expires_at AS approval_expires_at
FROM (SELECT $1::text AS agent_id, $2::text AS item_id, $3::timestamptz AS now) AS v
LEFT JOIN agents a ON a.id = v.agent_id
LEFT JOIN items i ON i.id = v.item_id
LEFT JOIN grants g ON g.agent_id = v.agent_id AND g.item_id = i.id
LEFT JOIN approvals ap ON ap.grant_id = g.id AND ap.expires_at > v.now
`

type UseAuthParams struct {
	AgentID string
	ItemID  string
	Now     pgtype.Timestamptz
}

type UseAuthRow struct {
	AgentID           pgtype.Text
	AgentOrgID        pgtype.Text
	AgentOwnerKind    pgtype.Text
	AgentOwnerID      pgtype.Text
	AgentRevokedAt    pgtype.Timestamptz
	ItemID            pgtype.Text
	ItemOrgID         pgtype.Text
	ItemName          pgtype.Text
	ItemKind          pgtype.Text
	ItemOwnerKind     pgtype.Text
	ItemOwnerID       pgtype.Text
	ItemUris          pgtype.Text
	ItemHasTotp       pgtype.Bool
	ItemTags          pgtype.Text
	ItemArchived      pgtype.Bool
	ItemHasFile       pgtype.Bool
	ItemLogin         pgtype.Text
	GrantID           pgtype.Text
	GrantOrgID        pgtype.Text
	GrantAgentID      pgtype.Text
	GrantItemID       pgtype.Text
	GrantLevel        pgtype.Text
	GrantActions      pgtype.Text
	GrantExpiresAt    pgtype.Timestamptz
	ApprovalID        pgtype.Text
	ApprovalGrantID   pgtype.Text
	ApprovalHumanID   pgtype.Text
	ApprovalExpiresAt pgtype.Timestamptz
}

func (q *Queries) UseAuth(ctx context.Context, arg UseAuthParams) (UseAuthRow, error) {
	row := q.db.QueryRow(ctx, useAuth, arg.AgentID, arg.ItemID, arg.Now)
	var i UseAuthRow
	err := row.Scan(
		&i.AgentID,
		&i.AgentOrgID,
		&i.AgentOwnerKind,
		&i.AgentOwnerID,
		&i.AgentRevokedAt,
		&i.ItemID,
		&i.ItemOrgID,
		&i.ItemName,
		&i.ItemKind,
		&i.ItemOwnerKind,
		&i.ItemOwnerID,
		&i.ItemUris,
		&i.ItemHasTotp,
		&i.ItemTags,
		&i.ItemArchived,
		&i.ItemHasFile,
		&i.ItemLogin,
		&i.GrantID,
		&i.GrantOrgID,
		&i.GrantAgentID,
		&i.GrantItemID,
		&i.GrantLevel,
		&i.GrantActions,
		&i.GrantExpiresAt,
		&i.ApprovalID,
		&i.ApprovalGrantID,
		&i.ApprovalHumanID,
		&i.ApprovalExpiresAt,
	)
	return i, err
}

const useAuthSession = `-- name: UseAuthSession :one
SELECT
    s.id AS session_id,
    a.id AS agent_id,
    a.org_id AS agent_org_id,
    a.owner_kind AS agent_owner_kind,
    a.owner_id AS agent_owner_id,
    a.revoked_at AS agent_revoked_at,
    i.id AS item_id,
    i.org_id AS item_org_id,
    i.name AS item_name,
    i.kind AS item_kind,
    i.owner_kind AS item_owner_kind,
    i.owner_id AS item_owner_id,
    i.uris AS item_uris,
    i.has_totp AS item_has_totp,
    i.tags AS item_tags,
    i.archived AS item_archived,
    i.has_file AS item_has_file,
    i.login AS item_login,
    g.id AS grant_id,
    g.org_id AS grant_org_id,
    g.agent_id AS grant_agent_id,
    g.item_id AS grant_item_id,
    g.level AS grant_level,
    g.actions AS grant_actions,
    g.expires_at AS grant_expires_at,
    ap.id AS approval_id,
    ap.grant_id AS approval_grant_id,
    ap.human_id AS approval_human_id,
    ap.expires_at AS approval_expires_at
FROM (SELECT $1::bytea AS session_hash, $2::text AS item_id, $3::timestamptz AS now) AS v
LEFT JOIN sessions s ON s.secret_hash = v.session_hash AND s.expires_at > v.now AND s.revoked_at IS NULL AND (s.max_uses = 0 OR s.uses < s.max_uses)
LEFT JOIN agents a ON a.id = s.agent_id
LEFT JOIN items i ON i.id = v.item_id
LEFT JOIN grants g ON g.agent_id = s.agent_id AND g.item_id = i.id
LEFT JOIN approvals ap ON ap.grant_id = g.id AND ap.expires_at > v.now
`

type UseAuthSessionParams struct {
	SessionHash []byte
	ItemID      string
	Now         pgtype.Timestamptz
}

type UseAuthSessionRow struct {
	SessionID         pgtype.Text
	AgentID           pgtype.Text
	AgentOrgID        pgtype.Text
	AgentOwnerKind    pgtype.Text
	AgentOwnerID      pgtype.Text
	AgentRevokedAt    pgtype.Timestamptz
	ItemID            pgtype.Text
	ItemOrgID         pgtype.Text
	ItemName          pgtype.Text
	ItemKind          pgtype.Text
	ItemOwnerKind     pgtype.Text
	ItemOwnerID       pgtype.Text
	ItemUris          pgtype.Text
	ItemHasTotp       pgtype.Bool
	ItemTags          pgtype.Text
	ItemArchived      pgtype.Bool
	ItemHasFile       pgtype.Bool
	ItemLogin         pgtype.Text
	GrantID           pgtype.Text
	GrantOrgID        pgtype.Text
	GrantAgentID      pgtype.Text
	GrantItemID       pgtype.Text
	GrantLevel        pgtype.Text
	GrantActions      pgtype.Text
	GrantExpiresAt    pgtype.Timestamptz
	ApprovalID        pgtype.Text
	ApprovalGrantID   pgtype.Text
	ApprovalHumanID   pgtype.Text
	ApprovalExpiresAt pgtype.Timestamptz
}

func (q *Queries) UseAuthSession(ctx context.Context, arg UseAuthSessionParams) (UseAuthSessionRow, error) {
	row := q.db.QueryRow(ctx, useAuthSession, arg.SessionHash, arg.ItemID, arg.Now)
	var i UseAuthSessionRow
	err := row.Scan(
		&i.SessionID,
		&i.AgentID,
		&i.AgentOrgID,
		&i.AgentOwnerKind,
		&i.AgentOwnerID,
		&i.AgentRevokedAt,
		&i.ItemID,
		&i.ItemOrgID,
		&i.ItemName,
		&i.ItemKind,
		&i.ItemOwnerKind,
		&i.ItemOwnerID,
		&i.ItemUris,
		&i.ItemHasTotp,
		&i.ItemTags,
		&i.ItemArchived,
		&i.ItemHasFile,
		&i.ItemLogin,
		&i.GrantID,
		&i.GrantOrgID,
		&i.GrantAgentID,
		&i.GrantItemID,
		&i.GrantLevel,
		&i.GrantActions,
		&i.GrantExpiresAt,
		&i.ApprovalID,
		&i.ApprovalGrantID,
		&i.ApprovalHumanID,
		&i.ApprovalExpiresAt,
	)
	return i, err
}
