// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const consumeSession = `-- name: ConsumeSession :one
UPDATE sessions s
SET uses = uses + 1
FROM agents a
WHERE s.secret_hash = $1::bytea
  AND s.agent_id = a.id
  AND a.revoked_at IS NULL
  AND s.expires_at > $2::timestamptz
  AND s.revoked_at IS NULL
  AND (s.max_uses = 0 OR s.uses < s.max_uses)
RETURNING a.id AS agent_id, a.org_id AS agent_org_id, a.owner_kind AS agent_owner_kind, a.owner_id AS agent_owner_id, a.revoked_at AS agent_revoked_at
`

type ConsumeSessionParams struct {
	SessionHash []byte
	Now         time.Time
}

type ConsumeSessionRow struct {
	AgentID        string
	AgentOrgID     string
	AgentOwnerKind string
	AgentOwnerID   string
	AgentRevokedAt sql.NullTime
}

func (q *Queries) ConsumeSession(ctx context.Context, arg ConsumeSessionParams) (ConsumeSessionRow, error) {
	row := q.db.QueryRow(ctx, consumeSession, arg.SessionHash, arg.Now)
	var i ConsumeSessionRow
	err := row.Scan(
		&i.AgentID,
		&i.AgentOrgID,
		&i.AgentOwnerKind,
		&i.AgentOwnerID,
		&i.AgentRevokedAt,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, org_id, agent_id, secret_hash, expires_at, created_at, revoked_at, renewed_at, ttl, max_ttl, max_uses, uses
FROM sessions ORDER BY expires_at LIMIT $1::bigint
`

func (q *Queries) ListSessions(ctx context.Context, maxResults int64) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessions, maxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AgentID,
			&i.SecretHash,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.RenewedAt,
			&i.Ttl,
			&i.MaxTtl,
			&i.MaxUses,
			&i.Uses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putSession = `-- name: PutSession :exec
INSERT INTO sessions(id, org_id, agent_id, secret_hash, expires_at, created_at, revoked_at, renewed_at, ttl, max_ttl, max_uses, uses)
VALUES($1::text, $2::text, $3::text, $4::bytea, $5::timestamptz, $6::timestamptz, $7, $8, $9::bigint, $10::bigint, $11::integer, $12::integer)
ON CONFLICT(id) DO UPDATE SET
    org_id=excluded.org_id,
    agent_id=excluded.agent_id,
    secret_hash=excluded.secret_hash,
    expires_at=excluded.expires_at,
    created_at=excluded.created_at,
    revoked_at=excluded.revoked_at,
    renewed_at=excluded.renewed_at,
    ttl=excluded.ttl,
    max_ttl=excluded.max_ttl,
    max_uses=excluded.max_uses,
    uses=excluded.uses
`

type PutSessionParams struct {
	ID         string
	OrgID      string
	AgentID    string
	SecretHash []byte
	ExpiresAt  time.Time
	CreatedAt  time.Time
	RevokedAt  sql.NullTime
	RenewedAt  sql.NullTime
	Ttl        int64
	MaxTtl     int64
	MaxUses    int32
	Uses       int32
}

func (q *Queries) PutSession(ctx context.Context, arg PutSessionParams) error {
	_, err := q.db.Exec(ctx, putSession,
		arg.ID,
		arg.OrgID,
		arg.AgentID,
		arg.SecretHash,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.RevokedAt,
		arg.RenewedAt,
		arg.Ttl,
		arg.MaxTtl,
		arg.MaxUses,
		arg.Uses,
	)
	return err
}

const renewSession = `-- name: RenewSession :exec
UPDATE sessions SET expires_at = $1::timestamptz, renewed_at = $2::timestamptz WHERE id = $3::text
`

type RenewSessionParams struct {
	ExpiresAt time.Time
	RenewedAt time.Time
	ID        string
}

func (q *Queries) RenewSession(ctx context.Context, arg RenewSessionParams) error {
	_, err := q.db.Exec(ctx, renewSession, arg.ExpiresAt, arg.RenewedAt, arg.ID)
	return err
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions SET revoked_at = COALESCE(revoked_at, $1::timestamptz) WHERE id = $2::text
`

type RevokeSessionParams struct {
	At time.Time
	ID string
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, arg.At, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sessionByHash = `-- name: SessionByHash :one
SELECT id, org_id, agent_id, secret_hash, expires_at, created_at, revoked_at, renewed_at, ttl, max_ttl, max_uses, uses
FROM sessions WHERE secret_hash = $1::bytea
`

func (q *Queries) SessionByHash(ctx context.Context, secretHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, sessionByHash, secretHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AgentID,
		&i.SecretHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.RenewedAt,
		&i.Ttl,
		&i.MaxTtl,
		&i.MaxUses,
		&i.Uses,
	)
	return i, err
}

const sessionByID = `-- name: SessionByID :one
SELECT id, org_id, agent_id, secret_hash, expires_at, created_at, revoked_at, renewed_at, ttl, max_ttl, max_uses, uses
FROM sessions WHERE id = $1::text
`

func (q *Queries) SessionByID(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, sessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AgentID,
		&i.SecretHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.RenewedAt,
		&i.Ttl,
		&i.MaxTtl,
		&i.MaxUses,
		&i.Uses,
	)
	return i, err
}

const useAuth = `-- name: UseAuth :one
SELECT
    a.id AS agent_id,
    a.org_id AS agent_org_id,
    a.owner_kind AS agent_owner_kind,
    a.owner_id AS agent_owner_id,
    a.revoked_at AS agent_revoked_at,
    i.id AS item_id,
    i.org_id AS item_org_id,
    i.name AS item_name,
    i.kind AS item_kind,
    i.owner_kind AS item_owner_kind,
    i.owner_id AS item_owner_id,
    i.uris AS item_uris,
    i.has_totp AS item_has_totp,
    i.tags AS item_tags,
    i.archived AS item_archived,
    i.has_file AS item_has_file,
    i.login AS item_login,
    g.id AS grant_id,
    g.org_id AS grant_org_id,
    g.agent_id AS grant_agent_id,
    g.item_id AS grant_item_id,
    g.level AS grant_level,
    g.actions AS grant_actions,
    g.expires_at AS grant_expires_at,
    ap.id AS approval_id,
    ap.grant_id AS approval_grant_id,
    ap.human_id AS approval_human_id,
    ap.expires_at AS approval_expires_at
FROM (SELECT $1::text AS agent_id, $2::text AS item_id, $3::timestamptz AS now) AS v
LEFT JOIN agents a ON a.id = v.agent_id
LEFT JOIN items i ON i.id = v.item_id
LEFT JOIN grants g ON g.agent_id = v.agent_id AND g.item_id = i.id
LEFT JOIN approvals ap ON ap.grant_id = g.id AND ap.expires_at > v.now
`

type UseAuthParams struct {
	AgentID string
	ItemID  string
	Now     time.Time
}

type UseAuthRow struct {
	AgentID           sql.NullString
	AgentOrgID        sql.NullString
	AgentOwnerKind    sql.NullString
	AgentOwnerID      sql.NullString
	AgentRevokedAt    sql.NullTime
	ItemID            sql.NullString
	ItemOrgID         sql.NullString
	ItemName          sql.NullString
	ItemKind          sql.NullString
	ItemOwnerKind     sql.NullString
	ItemOwnerID       sql.NullString
	ItemUris          sql.NullString
	ItemHasTotp       sql.NullBool
	ItemTags          sql.NullString
	ItemArchived      sql.NullBool
	ItemHasFile       sql.NullBool
	ItemLogin         sql.NullString
	GrantID           sql.NullString
	GrantOrgID        sql.NullString
	GrantAgentID      sql.NullString
	GrantItemID       sql.NullString
	GrantLevel        sql.NullString
	GrantActions      sql.NullString
	GrantExpiresAt    sql.NullTime
	ApprovalID        sql.NullString
	ApprovalGrantID   sql.NullString
	ApprovalHumanID   sql.NullString
	ApprovalExpiresAt sql.NullTime
}

func (q *Queries) UseAuth(ctx context.Context, arg UseAuthParams) (UseAuthRow, error) {
	row := q.db.QueryRow(ctx, useAuth, arg.AgentID, arg.ItemID, arg.Now)
	var i UseAuthRow
	err := row.Scan(
		&i.AgentID,
		&i.AgentOrgID,
		&i.AgentOwnerKind,
		&i.AgentOwnerID,
		&i.AgentRevokedAt,
		&i.ItemID,
		&i.ItemOrgID,
		&i.ItemName,
		&i.ItemKind,
		&i.ItemOwnerKind,
		&i.ItemOwnerID,
		&i.ItemUris,
		&i.ItemHasTotp,
		&i.ItemTags,
		&i.ItemArchived,
		&i.ItemHasFile,
		&i.ItemLogin,
		&i.GrantID,
		&i.GrantOrgID,
		&i.GrantAgentID,
		&i.GrantItemID,
		&i.GrantLevel,
		&i.GrantActions,
		&i.GrantExpiresAt,
		&i.ApprovalID,
		&i.ApprovalGrantID,
		&i.ApprovalHumanID,
		&i.ApprovalExpiresAt,
	)
	return i, err
}

const useAuthSession = `-- name: UseAuthSession :one
SELECT
    s.id AS session_id,
    a.id AS agent_id,
    a.org_id AS agent_org_id,
    a.owner_kind AS agent_owner_kind,
    a.owner_id AS agent_owner_id,
    a.revoked_at AS agent_revoked_at,
    i.id AS item_id,
    i.org_id AS item_org_id,
    i.name AS item_name,
    i.kind AS item_kind,
    i.owner_kind AS item_owner_kind,
    i.owner_id AS item_owner_id,
    i.uris AS item_uris,
    i.has_totp AS item_has_totp,
    i.tags AS item_tags,
    i.archived AS item_archived,
    i.has_file AS item_has_file,
    i.login AS item_login,
    g.id AS grant_id,
    g.org_id AS grant_org_id,
    g.agent_id AS grant_agent_id,
    g.item_id AS grant_item_id,
    g.level AS grant_level,
    g.actions AS grant_actions,
    g.expires_at AS grant_expires_at,
    ap.id AS approval_id,
    ap.grant_id AS approval_grant_id,
    ap.human_id AS approval_human_id,
    ap.expires_at AS approval_expires_at
FROM (SELECT $1::bytea AS session_hash, $2::text AS item_id, $3::timestamptz AS now) AS v
LEFT JOIN sessions s ON s.secret_hash = v.session_hash AND s.expires_at > v.now AND s.revoked_at IS NULL AND (s.max_uses = 0 OR s.uses < s.max_uses)
LEFT JOIN agents a ON a.id = s.agent_id
LEFT JOIN items i ON i.id = v.item_id
LEFT JOIN grants g ON g.agent_id = s.agent_id AND g.item_id = i.id
LEFT JOIN approvals ap ON ap.grant_id = g.id AND ap.expires_at > v.now
`

type UseAuthSessionParams struct {
	SessionHash []byte
	ItemID      string
	Now         time.Time
}

type UseAuthSessionRow struct {
	SessionID         sql.NullString
	AgentID           sql.NullString
	AgentOrgID        sql.NullString
	AgentOwnerKind    sql.NullString
	AgentOwnerID      sql.NullString
	AgentRevokedAt    sql.NullTime
	ItemID            sql.NullString
	ItemOrgID         sql.NullString
	ItemName          sql.NullString
	ItemKind          sql.NullString
	ItemOwnerKind     sql.NullString
	ItemOwnerID       sql.NullString
	ItemUris          sql.NullString
	ItemHasTotp       sql.NullBool
	ItemTags          sql.NullString
	ItemArchived      sql.NullBool
	ItemHasFile       sql.NullBool
	ItemLogin         sql.NullString
	GrantID           sql.NullString
	GrantOrgID        sql.NullString
	GrantAgentID      sql.NullString
	GrantItemID       sql.NullString
	GrantLevel        sql.NullString
	GrantActions      sql.NullString
	GrantExpiresAt    sql.NullTime
	ApprovalID        sql.NullString
	ApprovalGrantID   sql.NullString
	ApprovalHumanID   sql.NullString
	ApprovalExpiresAt sql.NullTime
}

func (q *Queries) UseAuthSession(ctx context.Context, arg UseAuthSessionParams) (UseAuthSessionRow, error) {
	row := q.db.QueryRow(ctx, useAuthSession, arg.SessionHash, arg.ItemID, arg.Now)
	var i UseAuthSessionRow
	err := row.Scan(
		&i.SessionID,
		&i.AgentID,
		&i.AgentOrgID,
		&i.AgentOwnerKind,
		&i.AgentOwnerID,
		&i.AgentRevokedAt,
		&i.ItemID,
		&i.ItemOrgID,
		&i.ItemName,
		&i.ItemKind,
		&i.ItemOwnerKind,
		&i.ItemOwnerID,
		&i.ItemUris,
		&i.ItemHasTotp,
		&i.ItemTags,
		&i.ItemArchived,
		&i.ItemHasFile,
		&i.ItemLogin,
		&i.GrantID,
		&i.GrantOrgID,
		&i.GrantAgentID,
		&i.GrantItemID,
		&i.GrantLevel,
		&i.GrantActions,
		&i.GrantExpiresAt,
		&i.ApprovalID,
		&i.ApprovalGrantID,
		&i.ApprovalHumanID,
		&i.ApprovalExpiresAt,
	)
	return i, err
}
